# Kustomization for Crossplane Claims
# Claims are namespace-scoped resources
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - my-webapp.yaml
  - team-api-app.yaml
  - demo-api-route.yaml

commonLabels:
  managed-by: argocd
  type: claim

